/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer */

#ifndef _Included_com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer
#define _Included_com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer
#include "ffmpegdecoder.h"
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer
 * Method:    stream
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer_stream
        (JNIEnv *env, jobject obj, jint minbufsize) {
    __android_log_print(ANDROID_LOG_DEBUG, TAG, "hello_jni");
    return stream(env, minbufsize);
}

/*
 * Class:     com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer
 * Method:    getDataSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer_getDataSize
        (JNIEnv *env, jobject obj) {
    return getDataSize();
}

/*
 * Class:     com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer
 * Method:    openFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer_openFile
(JNIEnv *env, jobject obj, jstring filename) {
    openFile(env, filename);
}

/*
 * Class:     com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer
 * Method:    getSampleRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer_getSampleRate
        (JNIEnv *env, jobject obj) {
    return getSampleRate();
}

/*
 * Class:     com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer
 * Method:    getChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer_getChannel
        (JNIEnv *env, jobject obj) {
    return getChannle();
}

/*
 * Class:     com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer
 * Method:    JNIInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer_JNIInit
(JNIEnv *env, jobject obj) {
    JNIInit();
}

/*
 * Class:     com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer
 * Method:    JNIExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest2_app_erdplayer_audioplayer_AudioPlayer_JNIExit
(JNIEnv *env, jobject obj) {
    JNIExit();
}

#ifdef __cplusplus
}
#endif
#endif
